# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: lein deps
    - name: Run test DB
      run: docker run -p 7500:5432 -e POSTGRES_USER=user -e POSTGRES_DB=tests -e POSTGRES_PASSWORD=password postgres:alpine
    - name: Run tests
      env:
        database-url: ${{ secrets.TEST_DB_URL }}
      run: lein test
    - name: Build
      if: success()
      run: lein uberjar
    - name: Login to Docker Hub
      if: success()
      uses: actions-hub/docker/login@master
      env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build image
      if: success()
      run: docker build -t  profunctorlense/hs-test-task:latest .
    - name: Push to docker hub
      if: success()
      uses: actions-hub/docker@master
      with:
        args: push profunctorlense/hs-test-task:latest
    - name: Create kubectl config
      if: success()
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      run: echo $KUBE_CONFIG | base64 -d > kubeconfig
    - name: Delete deployments/services on KubeSail
      if: success()
      run: kubectl --kubeconfig kubeconfig delete all --all
    - name: Deploy to KubeSail
      if: success()
      run: kubectl --kubeconfig kubeconfig apply -f deploy/postgres-master-deployment.yaml,deploy/postgres-master-service.yaml,deploy/patients-deployment.yaml,deploy/patients-service.yaml
      
  lint:
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: DeLaGuardo/clojure-lint-action@master
      with:
        clj-kondo-args: --lint src
        github_token: ${{ secrets.GITHUB_TOKEN }}
